[package]
name = "rp2040-test"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
embedded-hal = "1.0.0"
panic-halt = "0.2.0"
vcc-gnd-yd-rp2040 = "0.6.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
